### PR TITLE
Sync with omnition opentelemetry collector

### PR DESCRIPTION
**Pull request by owais**
This PR brings over the commits from omnition-opentelemetry-collector and adds some changes on top to prepare this repo as the default.

### CODE REVIEW

**Comment by owais** [comment]
Yes, most of it is brought in as is. Then a commit is added on top to fix deps and make it build. Commit title is "Synchronized the codebase with omnition-opentelemetry-collector" and current hash is `0097c6e525df59ac0f32241574ec4b6fe96f1376`

**Comment by owais** [comment]
This: https://github.com/signalfx/apm-opentelemetry-collector/pull/3/commits/0097c6e525df59ac0f32241574ec4b6fe96f1376

**Comment by owais** [comment]
Right. I'll close it.

**Comment by owais** [comment]
Actually, I merged it and rebased this on top to make sure I didn't miss anything.

**Comment by tigrannajaryan** [comment]
>Continuous integration has not been set up 

We need to also enable CI here.

**Comment by pjanotti** [comment]
@owais do we have a task logged to remove the custom zipkin? Just want to be sure that we don't forget once that reaches OTelCol.

**Comment by owais** [comment]
I'm trying to get k8s processor upstream. Once it is in, we won't need the custom receiver and can just remove them.

**Comment by owais** [comment]
https://github.com/signalfx/apm-opentelemetry-collector/issues/4

**Pull request merged**
